### ISSUE TITLE
Use jekyll serve to run local

### ISSUE THREAD

**Issue by bienflorencia** [gbif/hosted-portals#236]
Hello, 
I was trying to get a version of the portal running on my local computer to have a quick view of the changes. However `jekyll serve` is not working for me. Is local hosting an option, or I must do it through pushing to GitHub and gbif-staging? Thanks!

- ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
- Bundler version 2.3.22
- gem 3.3.7
- jekyll 4.2.2

This is my console output:
```
% jekyll serve 
/Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/git.rb:214:in `rescue in load_spec_files': https://github.com/gbif/jekyll-thumbor is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/git.rb:210:in `load_spec_files'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/path.rb:107:in `local_specs'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/git.rb:178:in `specs'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:194:in `block in specs_for_dependency'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:194:in `map'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:194:in `specs_for_dependency'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:33:in `block in for'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:22:in `loop'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:22:in `for'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:79:in `materialize'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/definition.rb:501:in `materialize'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/definition.rb:197:in `specs'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/definition.rb:254:in `specs_for'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/runtime.rb:18:in `setup'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler.rb:162:in `setup'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	from /Users/flograttarola/.gem/ruby/3.1.2/bin/jekyll:25:in `load'
	from /Users/flograttarola/.gem/ruby/3.1.2/bin/jekyll:25:in `<main>'
/Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/path.rb:209:in `load_spec_files': The path `/Users/flograttarola/.gem/ruby/3.1.2/bundler/gems/jekyll-thumbor-77df45e674bd` does not exist. (Bundler::PathError)
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/git.rb:211:in `load_spec_files'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/path.rb:107:in `local_specs'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/source/git.rb:178:in `specs'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:194:in `block in specs_for_dependency'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:194:in `map'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:194:in `specs_for_dependency'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:33:in `block in for'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:22:in `loop'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:22:in `for'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/spec_set.rb:79:in `materialize'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/definition.rb:501:in `materialize'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/definition.rb:197:in `specs'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/definition.rb:254:in `specs_for'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/runtime.rb:18:in `setup'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler.rb:162:in `setup'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Users/flograttarola/.gem/ruby/3.1.2/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	from /Users/flograttarola/.gem/ruby/3.1.2/bin/jekyll:25:in `load'
	from /Users/flograttarola/.gem/ruby/3.1.2/bin/jekyll:25:in `<main>'
```

Thanks!

**Comment by MortenHofft** [comment]
Hi Flo - good idea to run it locally. It makes development much faster. And it should work just fine.

First line in your error message says `Run 'bundle install' first. (Bundler::GitError)`

But even had you done that I'm not sure it would work as you use Jekyll version 4. I've updated your dependencies, so that it should now work with Jekyll 4. But you still need to install before serving.

You should be able to do:
```
bundle install
bundle exec jekyll serve
```

Did that help?

**Comment by bienflorencia** [comment]
Yes! I had to update `bundle` first, as it was not working with ruby 3.1. After it worked fine. 
Thanks a lot, Morten! This is gonna make it easier to test stuff.

**Comment by MortenHofft** [comment]
let me know if we now have issues building on server, since that might be using a different version of the bundler etc.

**Comment by bienflorencia** [comment]
No issues, I just pushed some changes and seems to be working fine. Thanks!
